# Generated by Django 3.2.25 on 2026-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Palabra clave')),
                ('total_encontradas', models.IntegerField(default=0, verbose_name='Encontradas')),
                ('nuevas', models.IntegerField(default=0, verbose_name='Nuevas')),
                ('existentes', models.IntegerField(default=0, verbose_name='Ya registradas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de búsqueda')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID API')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Salario mínimo')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Salario máximo')),
                ('currency_type', models.CharField(blank=True, max_length=10, verbose_name='Moneda')),
                ('posted_date', models.CharField(blank=True, max_length=50, verbose_name='Fecha de publicación')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fuente')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='Logo URL')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Habilidades')),
                ('level_rank', models.IntegerField(default=5, verbose_name='Rango de nivel')),
                ('level', models.CharField(blank=True, max_length=30, verbose_name='Nivel')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL original')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('busquedas', models.ManyToManyField(blank=True, related_name='ofertas', to='empleos.Busqueda')),
            ],
            options={
                'verbose_name': 'Oferta de empleo',
                'verbose_name_plural': 'Ofertas de empleo',
                'ordering': ['-created'],
            },
        ),
    ]
