# Generated by Django 3.2.25 on 2026-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='api_id',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='ID API'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='source',
            field=models.CharField(blank=True, max_length=250, verbose_name='Fuente'),
        ),
    ]
