# Generated by Django 3.2.25 on 2026-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_auto_20260818_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
