# Generated by Django 3.2.25 on 2026-08-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_alter_ofertaempleo_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='api_id',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='ID API'),
        ),
    ]
