# Generated by Django 3.2.25 on 2026-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_alter_ofertaempleo_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='oculto',
            field=models.BooleanField(default=False, verbose_name='Oculto'),
        ),
    ]
