# Generated by Django 3.2.25 on 2026-08-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0006_auto_20260818_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del filtro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('keywords', models.TextField(blank=True, help_text='Separadas por coma. Ej: python, django, linux', verbose_name='Palabras clave')),
                ('country_id', models.IntegerField(blank=True, help_text='Ej: 1 = Perú', null=True, verbose_name='País (ID)')),
                ('from_age', models.IntegerField(blank=True, help_text='Ej: 1 = último día', null=True, verbose_name='Antigüedad en días')),
                ('type_order', models.IntegerField(blank=True, null=True, verbose_name='Orden de tipo')),
                ('job_seniority', models.JSONField(blank=True, default=list, help_text='IDs: 1 Prácticas, 2 Junior, 3 Semi Senior, 4 Senior', verbose_name='Niveles (seniority)')),
                ('work_modality_id', models.JSONField(blank=True, default=list, verbose_name='Modalidad de trabajo')),
                ('job_category_id', models.JSONField(blank=True, default=list, verbose_name='Categoría')),
                ('job_type_id', models.JSONField(blank=True, default=list, verbose_name='Tipo de empleo')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Salario mínimo')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Salario máximo')),
                ('currency_type', models.CharField(blank=True, max_length=10, verbose_name='Moneda')),
                ('p_english_req', models.BooleanField(blank=True, null=True, verbose_name='¿Requiere inglés?')),
                ('max_pages', models.IntegerField(default=3, verbose_name='Máx. páginas por keyword')),
                ('email_destino', models.EmailField(blank=True, help_text='Vacío = usa el email configurado en el .env', max_length=254, verbose_name='Email de destino')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Vacío = usa el chat ID del .env', max_length=64, verbose_name='Telegram chat ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Filtro de empleo',
                'verbose_name_plural': 'Filtros de empleo',
                'ordering': ['-created'],
            },
        ),
    ]
