# Generated by Django 3.2.25 on 2026-08-12 01:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_iplocation_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (S/)')),
                ('caracteristicas', models.JSONField(blank=True, default=list, help_text='Lista de características. Una por elemento, ej. ["Punto de venta", "Facturación"].', verbose_name='Características')),
                ('icono', models.CharField(default='fas fa-cogs', help_text='Clase de FontAwesome, ej. "fas fa-cash-register".', max_length=80, verbose_name='Ícono (FontAwesome)')),
                ('color', models.CharField(default='primary', help_text='Nombre del color de acento: blue, amber, purple, pink, teal, yellow, indigo, slate o primary.', max_length=30, verbose_name='Color (Tailwind)')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado / Recomendado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
