# Generated by Django 3.2.25 on 2026-08-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0013_auto_20251121_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
