# Generated by Django 3.2.25 on 2026-03-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrada', '0013_auto_20251121_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='entrada.entry')),
            ],
        ),
    ]
