# Generated by Django 3.2.25 on 2025-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL de la imagen de Google', null=True, verbose_name='URL Avatar Google'),
        ),
    ]
