# Generated by Django 3.2.25 on 2026-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Usuario'), ('2', 'Otro')], max_length=1),
        ),
    ]
