# Generated by Django 3.0.4 on 2025-09-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
